#! /bin/bash

# Install XCode / XCode CLI tools
if command -v xcode-select &> /dev/null; then
	echo "Xcode installed, installing commandline tools if not already installed"
	xcode-select --install 2> /dev/null
	echo "Successfully installed xcode-cli tools"
else
	echo "Xcode is not installed, would you like to install it now? (y/n)"
	read installXCode
	if [ $installXCode = "y"] || [ $installXCode = "yes" ]; then
		echo "Opening up the browser to the app stores Xcode page"
		open https://itunes.apple.com/us/app/xcode/id497799835?mt=12
		echo "After installing XCode, please rerun the script and xcode tools shall be installed upon next run"
	else
		echo " Xcode is needed for anything else to install. Shutting down."
	exit
	fi
fi

# Installing brew pkg manager
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
